spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "2.0"
cards:
  message: "Welcome to bank Loans related QA APIs"
  contactDetails:
    name: "Bhaskar Chauhan "
    email: "Bhaskar123@gmail.com"
  onCallSupport:
    -(888)999-1234