build:
  version: "2.0"
accounts:
  message: "Welcome to bank accounts related QA APIs"
  contactDetails:
    name: "madhav singh - QA"
    email: "Madhav123@gmail.com"
  onCallSupport:
    -(555)8599-2222
