server:
  port: 8075
eureka:
  #instance:
    #hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8075/eureka/




