build:
  version: "1.0"
cards:
  message: "Welcome to bank Loans related Prod APIs"
  contactDetails:
    name: "Bhaskar Chauhan "
    email: "Bhaskar123@gmail.com"
  onCallSupport:
    -(888)999-1234